package com.sess.core.components.message;

public enum  MessageId {

    UNIQUE_NICKNAME_VIOLATION, UNIQUE_EMAIL_VIOLATION, FAILED_SAVE_NEW_USER, READ_DTO_USER_DATA_ERROR, WRITE_DTO_USER_DATA_ERROR, WRITE_DTO_EVENT_DATA_ERROR, NOT_NULLABLE_USER_ID

}
