package com.sess.core.components.message;

public enum  MessageId {

    UNIQUE_NICKNAME_VIOLATION, UNIQUE_EMAIL_VIOLATION, FAILED_SAVE_NEW_USER, READ_DTO_USER_DATA_ERROR, WRITE_DTO_USER_DATA_ERROR, WRITE_DTO_EVENT_DATA_ERROR, NOT_NULLABLE_GROUP_ID, GROUP_NOT_FOUND, USER_NOT_FOUND, USER_ALREADY_EXIST_IN_GROUP, GROUP_TITLE_ALREADY_EXISTS, USER_NOT_FOUND_IN_GROUP, NOT_NULLABLE_RUNNING_TYPE_ID, RUNNING_TYPE_CAPTION_ALREADY_EXISTS_IN_GROUP, RUNNING_TYPE_NOT_FOUND, NOT_NULLABLE_EVENT_ID, DURING_CREATE_FACTUAL_DATES_MUST_BE_NULL, EVENT_NOT_FOUND, EVENT_CAN_NOT_BE_CHANGED, NOT_NULLABLE_USER_ID

}
